In [7]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/DataCoSupplyChainDataset.csv", encoding="latin1")

df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [8]:
df = df.drop_duplicates()

In [9]:
important_cols = [
    "Type",
    "Days for shipping (real)",
    "Days for shipment (scheduled)",
    "Benefit per order",
    "Sales per customer",
    "Delivery Status",
    "Late_delivery_risk",
    "Category Name",
    "Customer Segment",
    "Market",
    "Order Region",
    "Order State",
    "Order Status",
    "Order Item Discount",
    "Order Item Discount Rate",
    "Order Item Product Price",
    "Order Item Profit Ratio",
    "Order Item Quantity",
    "Sales",
    "Order Item Total",
    "Order Profit Per Order",
    "Product Price",
    "Shipping Mode"
]

df = df[important_cols]
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Name,Customer Segment,Market,...,Order Item Discount,Order Item Discount Rate,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Product Price,Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,Sporting Goods,Consumer,Pacific Asia,...,13.110000,0.04,327.75,0.29,1,327.75,314.640015,91.250000,327.75,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,Sporting Goods,Consumer,Pacific Asia,...,16.389999,0.05,327.75,-0.80,1,327.75,311.359985,-249.089996,327.75,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,Sporting Goods,Consumer,Pacific Asia,...,18.030001,0.06,327.75,-0.80,1,327.75,309.720001,-247.779999,327.75,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,Sporting Goods,Home Office,Pacific Asia,...,22.940001,0.07,327.75,0.08,1,327.75,304.809998,22.860001,327.75,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,Sporting Goods,Corporate,Pacific Asia,...,29.500000,0.09,327.75,0.45,1,327.75,298.250000,134.210007,327.75,Standard Class

In [10]:
df.isnull().sum()

Type                             0
Days for shipping (real)         0
Days for shipment (scheduled)    0
Benefit per order                0
Sales per customer               0
Delivery Status                  0
Late_delivery_risk               0
Category Name                    0
Customer Segment                 0
Market                           0
Order Region                     0
Order State                      0
Order Status                     0
Order Item Discount              0
Order Item Discount Rate         0
Order Item Product Price         0
Order Item Profit Ratio          0
Order Item Quantity              0
Sales                            0
Order Item Total                 0
Order Profit Per Order           0
Product Price                    0
Shipping Mode                    0
dtype: int64

In [11]:
df = df.dropna()

In [12]:
df["Delay_Gap"] = df["Days for shipping (real)"] - df["Days for shipment (scheduled)"]

df["Shipping_Pressure_Index"] = (
    df["Order Item Quantity"] / (df["Days for shipment (scheduled)"] + 1)
)

df["Order_Complexity_Score"] = (
    df["Order Item Quantity"] * df["Product Price"]
)

df["Profit_Sensitivity"] = (
    df["Order Profit Per Order"] / (df["Sales"] + 1)
)

df["Discount_Impact"] = (
    df["Order Item Discount Rate"] * df["Order Item Product Price"]
)

In [13]:
df["Risk_Category"] = pd.cut(
    df["Late_delivery_risk"],
    bins=[-1, 0, 1],
    labels=["Low Risk", "High Risk"]
)

In [14]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Name,Customer Segment,Market,...,Order Item Total,Order Profit Per Order,Product Price,Shipping Mode,Delay_Gap,Shipping_Pressure_Index,Order_Complexity_Score,Profit_Sensitivity,Discount_Impact,Risk_Category
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,Sporting Goods,Consumer,Pacific Asia,...,314.640015,91.250000,327.75,Standard Class,-1,0.2,327.75,0.277567,13.110000,Low Risk
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,Sporting Goods,Consumer,Pacific Asia,...,311.359985,-249.089996,327.75,Standard Class,1,0.2,327.75,-0.757688,16.387500,High Risk
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,Sporting Goods,Consumer,Pacific Asia,...,309.720001,-247.779999,327.75,Standard Class,0,0.2,327.75,-0.753703,19.665000,Low Risk
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,Sporting Goods,Home Office,Pacific Asia,...,304.809998,22.860001,327.75,Standard Class,-1,0.2,327.75,0.069536,22.942500,Low Risk
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,Sporting Goods,Corporate,Pacific Asia,...,298.250000,134.210007,327.75,Standard Class,-2,0.2,327.75,0.408243,29.497501,Low Risk

In [17]:
df.to_csv("../data/processed/cleaned_data.csv", index=False)

print("Cleaned data saved successfully!")
print(df.shape)

Cleaned data saved successfully!
(180468, 29)